### ISSUE TITLE
Calendar date

### ISSUE THREAD

**Issue by Amitamon2** [tabhresh/Edureka_4th_March#1]
Hi,

Please share a piece of code for selecting or choosing date from calendar.

I was working on https://www.goindigo.in/?linkNav=home_header.

Also, the no. of passengers question on this web page from Module 4 is also not happening.

Tried the solution but that is failing anyway. Please help.

Thanks
Amita

**Comment by tabhresh** [comment]
Share the script pls

**Comment by Amitamon2** [comment]
`package com.Mod4;

import java.awt.SecondaryLoop;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.server.handler.SendKeys;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Driver_Controls {

	static WebDriver driver ;

	public static ChromeDriver launchChrome() {	
		System.setProperty("webdriver.chrome.driver", "F:\\Edureka\\Course\\Drivers\\chromedriver.exe");
		return new ChromeDriver();
	}

	public static void main(String[] args) {
		driver = launchChrome();

		//Launch the browser with “https://www.goindigo.in/?linkNav=home_header”
		driver.get("https://www.goindigo.in/?linkNav=home_header");
		driver.manage().timeouts().implicitlyWait(100, TimeUnit.SECONDS);

		//Select “One way” in the option
		driver.findElement(By.name("tripTabs")).click();

		//Fill all the details 
		WebElement from = driver.findElement(By.cssSelector("#bookFlightTab > form > div.or-tab-content.trip-tab-content > div:nth-child(1) > div.col-sm-5.col-5.padd-left > div > div > input"));
		WebElement to = driver.findElement(By.cssSelector("#bookFlightTab > form > div.or-tab-content.trip-tab-content > div:nth-child(1) > div.col-sm-5.col-5.padd-right > div > div > input"));
		
		from.click();
		driver.findElement(By.xpath("//div[@data-iata='BLR' and @data-keywords='Bangalore']")).click();
		
		to.sendKeys("Lucknow, India");
		
		driver.findElement(By.xpath("//*[@id=\"bookFlightTab\"]/form/div[5]/div[1]/div[1]/input")).click();
		
		WebDriverWait wait = new WebDriverWait(driver,100);
		
		WebElement adult = driver.findElement(By.xpath("//*[@id=\"bookFlightTab\"]/form/div[5]/div[1]/div[2]/ul/li[1]/div/button[2]/span"));
		System.out.println(adult.isEnabled());
		
		
		
		//driver.findElement(By.cssSelector("#bookFlightTab > form > div.or-tab-content.trip-tab-content > div.row.justify-content-around.ie-justify-dest > div.col-sm-5.col-5.padd-left > div > input")).sendKeys(Keys.ENTER);;
		
		
		
	

	}

}
`

**Comment by tabhresh** [comment]
1) import java.awt.SecondaryLoop;
What is the use of this import?
2) Remove all the unwanted Imports
3) execution is working at my end
4) Pls use the comments so that I can understand which command u have used for what action?
5) Xpath is not correct as I was unable to find this xpath relating to any element
WebElement adult = driver.findElement(By.xpath("//*[@id=\"bookFlightTab\"]/form/div[5]/div[1]/div[2]/ul/li[1]/div/button[2]/span"));
	System.out.println(adult.isEnabled());
