### ISSUE TITLE
Module 3- case study-navigate back is not working, and unable to validate timeout/implicit/explicit wait working properly

### ISSUE THREAD

**Issue by sikhap** [tabhresh/Edureka_4th_March#2]
`package module3;

import java.util.concurrent.TimeUnit;

import org.junit.rules.Timeout;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class XpathAssignment {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		// Open Chrome Browser
		   System.setProperty("webdriver.chrome.driver", "C:\\Users\\GIRI_HOME_PC_HP\\Selenium\\InstallationStuff\\ExeFiles\\chromedriver.exe");
		   WebDriver driver = new ChromeDriver();

		/*// Open Firefox Browser
		   System.setProperty("webdriver.gecko.driver", "C:\\Users\\GIRI_HOME_PC_HP\\Selenium\\InstallationStuff\\ExeFiles\\geckodriver.exe");
		   WebDriver FF = new FirefoxDriver(); */
		   
		//  Browser Page load
		   driver.manage().timeouts().pageLoadTimeout(50, TimeUnit.SECONDS);
		   
		//Open the Web page
			driver.get("https://www.edureka.co/");
		   
		   //driver.get("http://newtours.demoaut.com/");
		   
		   // driver.get("https://www.facebook.com");
		  //  driver.manage().window().maximize();
		    
		// Page implicit wait
		    driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);
		    
		// find_element_by_id
		    driver.findElement(By.id("search-inp")).sendKeys("Selenium");
		    driver.findElement(By.xpath("//*[@id='search-button-top']")).click();
		    
		 // Page explicit wait
		 	WebDriverWait wait = new WebDriverWait(driver, 50);		
		 	WebElement course = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/section/div[2]/div[2]/div/div[2]/div[2]/a[1]/div[1]/div[2]/div[1]/h3")));
		 	course.click(); 
		 	
		 //	driver.findElement(By.xpath("/html/body/div[2]/section/div[2]/div[2]/div/div[2]/div[2]/a[1]/div[1]/div[2]/div[1]/h3")).click();			
		    
		 // Page implicit wait
		    driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);  
		    
		 // find_element_by_id   
		   
		    String PgTitle = driver.getTitle();

			System.out.println(PgTitle);
				
			boolean result = PgTitle.equals("Selenium Training | Selenium Certification Course- Edureka");
			
			System.out.println(result);
			
		// navigate back
		
			Thread.sleep(5000);
			driver.navigate().back();     
	}
}
`

**Comment by tabhresh** [comment]
I was unable to see any issues into the script
