### ISSUE TITLE
Module 4 case study- 1. unable to deselect/select radiobutton 2. Getting NoSuchElementException for 'From' 

### ISSUE THREAD

**Issue by sikhap** [tabhresh/Edureka_4th_March#3]
package module4;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Module4_CaseStudy {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		// Open Chrome Browser
		   System.setProperty("webdriver.chrome.driver", "C:\\Users\\GIRI_HOME_PC_HP\\Selenium\\InstallationStuff\\ExeFiles\\chromedriver.exe");
		   WebDriver driver = new ChromeDriver();

		/*// Open Firefox Browser
		   System.setProperty("webdriver.gecko.driver", "C:\\Users\\GIRI_HOME_PC_HP\\Selenium\\InstallationStuff\\ExeFiles\\geckodriver.exe");
		   WebDriver FF = new FirefoxDriver(); */
		   
		 //Open the Web page
			driver.get("https://www.goindigo.in/?linkNav=home_header");
		 //	driver.manage().window().maximize();
			
			WebElement radiobutton1 = driver.findElement(By.id("oneWayTrip"));							
	        WebElement radiobutton2 = driver.findElement(By.id("roundTrip"));
	        WebElement radiobutton3 = driver.findElement(By.id("multiCity"));
			
		  //Radio Button1 is selected		
	        radiobutton1.click();			
	        System.out.println("Radio Button Option oneWayTrip Selected");					
	        		
	    /*  //Radio Button1 is de-selected and Radio Button2 is selected		
	        radiobutton2.click();			
	        System.out.println("Radio Button Option roundTrip Selected");	
	        
	       //Radio Button2 is de-selected and Radio Button3 is selected
	        radiobutton3.click();			
	        System.out.println("Radio Button Option multiCity Selected");
	        
	        //Radio Button3 is de-selected and Radio Button1 is selected
	        radiobutton1.click();			
	        System.out.println("Radio Button Option multiCity Selected");
	        
	        // DESELECT RADIO BUTTON3 AND SELECT RADIO BUTTON IS NOT WORKING
	        	*/
	        
	       
	        driver.manage().timeouts().implicitlyWait(20,TimeUnit.SECONDS);  
	        
	     //Select From City
	        
	         driver.findElement(By.xpath("/html/body/div[2]/section/div/div[2]/div/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[1]/div/div/input")).sendKeys("BLR");
	       
	      // GETTING NOSUCHELEMENTEXCEPTION ERROR AT ABOVE LINE FOR FROM CITY -   
	         driver.findElement(By.cssSelector(".or-src-city"));
	         driver.findElement(By.linkText("Bengaluru (BLR)")).click();
        
	         
	      //Select To City
	        driver.findElement(By.xpath("/html/body/div[2]/section/div/div[2]/div/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[2]/div/div/input")).sendKeys("LKO");

	        driver.findElement(By.linkText("Lucknow (LKO)")).click();

	      //Select number of Passengers
		    Select PsgDropdown = new Select(driver.findElement(By.name("Adult(s)"))); 

		    PsgDropdown.selectByValue("3");
	        
	}

}

**Comment by tabhresh** [comment]
radio button is not an element which can be deselected!

**Comment by tabhresh** [comment]
I tried your script there are many normal xpath used try going for customized xpath and use them.
