### ISSUE TITLE
Module 9:  Error occurred during initialization of boot layer

### ISSUE THREAD

**Issue by jamymathew** [tabhresh/Edureka_4th_March#4]
https://github.com/jamymathew/Hello-World

**Comment by tabhresh** [comment]
error was path of the Sheet was not having double forward slash and even the imports were incorrect.

**Comment by jamymathew** [comment]
Hi Abhresh,

I am using Mac OS and the file format doesn't need double slash.

Can you be more specific on the Imports.  Eclipse is not showing any error in Imports.
My code is error free and when I run , its throws the error mentioned even before opening the browser.

This happens  only when I use POI projects.

Is there any chance of incompatibility between the versions of java, eclipse  , POI, TestNG and all?
