### ISSUE TITLE
Module 4 : Calendar date selection and Passenger List 

### ISSUE THREAD

**Issue by Amitamon2** [tabhresh/Edureka_4th_March#5]
package com.Mod4;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.server.handler.SendKeys;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Driver_Controls {

	static WebDriver driver ;

	public static ChromeDriver launchChrome() {	
		System.setProperty("webdriver.chrome.driver", "F:\\Edureka\\Course\\Drivers\\chromedriver.exe");
		return new ChromeDriver();
	}

	public static void main(String[] args) {
		driver = launchChrome();

		//Launch the browser with “https://www.goindigo.in/?linkNav=home_header”
		driver.get("https://www.goindigo.in/?linkNav=home_header");
		driver.manage().timeouts().implicitlyWait(100, TimeUnit.SECONDS);

		//Select “One way” in the option
		driver.findElement(By.name("tripTabs")).click();

		//Fill all the details 
		//selecting Bangaluru and Lucknow
		WebElement from = driver.findElement(By.cssSelector("#bookFlightTab > form > div.or-tab-content.trip-tab-content > div:nth-child(1) > div.col-sm-5.col-5.padd-left > div > div > input"));
		WebElement to = driver.findElement(By.cssSelector("#bookFlightTab > form > div.or-tab-content.trip-tab-content > div:nth-child(1) > div.col-sm-5.col-5.padd-right > div > div > input"));
		
		from.click();
		driver.findElement(By.xpath("//div[@data-iata='BLR' and @data-keywords='Bangalore']")).click();
		
		to.sendKeys("Lucknow, India");
		
		//Calendar Date Selection
		/*Unable to select a date from dynamic calender*/
		
		driver.findElement(By.xpath("//*[@id=\"bookFlightTab\"]/form/div[5]/div[1]/div[1]/input")).click();
		
		//Pasenger no. from that + and - buttons
		/*
		WebDriverWait wait = new WebDriverWait(driver,100);
		
		WebElement adult = driver.findElement(By.xpath("//*[@id=\"bookFlightTab\"]/form/div[5]/div[1]/div[2]/ul/li[1]/div/button[2]/span"));
		System.out.println(adult.isEnabled());
		
		
		
		driver.findElement(By.cssSelector("#bookFlightTab > form > div.or-tab-content.trip-tab-content > div.row.justify-content-around.ie-justify-dest > div.col-sm-5.col-5.padd-left > div > input")).sendKeys(Keys.ENTER);;
		
		*/
		
	

	}

}

**Comment by tabhresh** [comment]
Update the script with customized Xpath.. the search for this Xpath working...

**Comment by tabhresh** [comment]
//Try Using this kind of process


package Extras;
 
import java.util.List;
 
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
 
public class CalendarHandling {
 
	public static void main(String[] args) 
	{
		
		System.setProperty("webdriver.chrome.driver", "E:\\Abhresh\\Installation_stuff\\ExeFiles\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();

		driver.get("WEBSITE URL");
		
		driver.findElement(By.id("===")).click();
					
		List<WebElement> allDates=driver.findElements(By.xpath("==="));
		
		for(WebElement ele:allDates)
		{
			
			String date=ele.getText();
			
			if(date.equalsIgnoreCase("28"))
			{
				ele.click();
				break;
}}}}

**Comment by Amitamon2** [comment]
Great ... I  will try that.

Thanks Abhresh :)


Regards,
Amita
